name: Manual run Cypress Tests

on:
  workflow_dispatch:

jobs:
  e2e:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"

      - name: Install yarn
        run: npm i -g yarn

      - name: Run cypress
        run: |
          cd test
          npm install
          npx cypress run

      - name: Screenshots upload
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: test/screenshots

      - name: Send Notification to Slack if Success
        uses: slackapi/slack-github-action@v1.24.0
        if: success()
        with:
          channel-id: "CHANNEL_ID"
          payload: | 
            {
              "text": "GitHub Action build result: ${{ job.status }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}
          GH_TOKEN: ${{ github.token }}
       
      - name: Send Notification to Slack if Failure
        uses: slackapi/slack-github-action@v1.24.0
        if: failure() 
        with:
          channel-id: "CHANNEL_ID"
          payload: | 
            {
              "text": "GitHub Action build result: ${{ job.status }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}
          GH_TOKEN: ${{ github.token }}